version: "3"

services:
  redis_service:
    image: redis::latest
    container_name: redis-server
    ports:
      - 6379:6379

  mafia-server:

    # build:
    #   context: .
    #   dockerfile: Dockerfiles/server.Dockerfile
    image: kseniac/mafia_components:server
    container_name: mafia-server
    ports:
      - 5002:5002
    environment:
      - PORT=5002
  
  mafia-bot-1:

    # build:
    #   context: .
    #   dockerfile: Dockerfiles/client_bot.Dockerfile
    depends_on:
      - mafia-server
    image: kseniac/mafia_components:client_bot
    container_name: mafia-bot-1
    environment:
      - NAME=saura
      - PORT=5002

  mafia-bot-2:
    depends_on:
      - mafia-server
    # build:
    #   context: .
    #   dockerfile: Dockerfiles/client_bot.Dockerfile
    image: kseniac/mafia_components:client_bot
    container_name: mafia-bot-2
    environment:
      - NAME=vieran
      - PORT=5002

  mafia-bot-3:
    depends_on:
      - mafia-server
    # build:
    #   context: .
    #   dockerfile: Dockerfiles/client_bot.Dockerfile
    image: kseniac/mafia_components:client_bot
    container_name: mafia-bot-3
    environment:
      - NAME=meccury
      - PORT=5002
  